---
- name: Make temporary download directory
  tempfile:
    state: directory
  register: thelounge_tmp_dir

- name: Set url latest uri
  set_fact:
    thelounge_api_url: '{{ thelounge_latest_url }}'
  when:
    thelounge_version == 'latest'

- name: Set url to release uri
  set_fact:
    thelounge_api_url: '{{ thelounge_release_url }}'
  when:
    thelounge_version != 'latest'

- name: Get the desired release info
  uri:
    url: '{{ thelounge_api_url }}'
    return_content: true
  register: lounge_json_response
  failed_when: lounge_json_response.json.assets.0.content_type !=
    'application/x-debian-package'
  when:
    - thelounge_version is not search("pre")

- name: Get the .deb file
  get_url:
    url: '{{ lounge_json_response.json.assets.0.browser_download_url }}'
    dest: '{{ thelounge_tmp_dir.path }}'
  register: thelounge_deb_path
  when:
    - lounge_json_response is defined
    - lounge_json_response is not skipped

- name: Install thelounge deb
  apt:
    deb: '{{ thelounge_deb_path.dest }}'
  when:
    - thelounge_deb_path is defined
    - thelounge_deb_path is not skipped

- name: Remove the temp download dir
  file:
    state: absent
    path: '{{ thelounge_tmp_dir.path }}'
