---
- name: Make temporary download directory
  tempfile:
    state: directory
  register: thelounge_tmp_dir

- name: Get the latest release info
  uri:
    url: https://api.github.com/repos/thelounge/thelounge/releases/latest
    return_content: true
  register: lounge_json_response
  failed_when: lounge_json_response.json.assets.0.content_type != "application/x-debian-package"
  when:
    - thelounge_version == 'latest'

- name: Get a specific tagged release
  uri:
    url: 'https://api.github.com/repos/thelounge/thelounge/releases/tags/v{{ thelounge_version }}'
    return_content: true
  register: lounge_json_response
  failed_when: lounge_json_response.json.assets.0.content_type != "application/x-debian-package"
  when:
    - thelounge_version != 'latest'
    - thelounge_version is not search("pre")

- name: Get the .deb file
  get_url: 
    url: '{{ lounge_json_response.json.assets.0.browser_download_url }}'
    dest: '{{ thelounge_tmp_dir.path }}'
  register: thelounge_deb_path
  when:
    - lounge_json_response is defined

- name: Install thelounge deb
  apt:
    deb: '{{ thelounge_deb_path }}'
  when:
    - lounge_json_response is defined

- name: Remove the temp download dir
  file:
    state: absent
    path: '{{ thelounge_tmp_dir.path }}'