---
- name: Get the latest release info
  uri:
    url: https://api.github.com/repos/thelounge/thelounge/releases/latest
    return_content: true
  register: lounge_json_response
  failed_when: lounge_json_response.json.assets.0.content_type != "application/x-debian-package"

- name: Get the latest thelounge .deb
  get_url: 
    url: '{{ lounge_json_response.json.assets.0.browser_download_url }}'
    dest: /root/thelounge.deb

- name: Install thelounge
  apt:
    deb: /root/thelounge.deb